### ISSUE TITLE
v1.0.0 变动细节注意要点

### ISSUE THREAD

**Issue by JaxsonWang** [JaxsonWang/WTF-Theme#2]
### 资源

请及时更换 `app.min.js/app.min.css` 文件

### 布局改动

- `index.html` 改动：[`navbar-expand-lg` 修改为 `navbar-expand-md`](https://github.com/JaxsonWang/Frenemy/blob/7cec824977635618644a442e6c4464042da43b41/index.html#L14)

- `index.html` 改动：[优化版权信息](https://github.com/JaxsonWang/Frenemy/blob/7cec824977635618644a442e6c4464042da43b41/index.html#L325)

- `index.html` 改动：[添加备案号显示和部分信息显示](https://github.com/JaxsonWang/Frenemy/blob/7cec824977635618644a442e6c4464042da43b41/index.html#L334-L340)

- `index.html`改动：[修改回到顶部按钮类名 (class) ](https://github.com/JaxsonWang/Frenemy/blob/7cec824977635618644a442e6c4464042da43b41/index.html#L342)

### 添加功能

添加搜索和夜晚模式按钮：[nav 导航栏菜单](https://github.com/JaxsonWang/Frenemy/blob/7cec824977635618644a442e6c4464042da43b41/index.html#L31-L52)

### 改动检索

请参考：[7cec824](https://github.com/JaxsonWang/Frenemy/commit/7cec824977635618644a442e6c4464042da43b41)

### 其它

**日夜模式样式添加：**

对于特定的平台会出现特定样式，如果需要支持添加护眼模式的样式，语法很简单。在该主题中最顶级 `class` 是 `[data-theme="dark"]`，只需要把他当作父类选择器即可：

```css
[data-theme="dark"] section.example {
  background-color: #080808;
  color: #b7b7b7;
}
```

> 在黑暗模式中 类名为 `example`  section 页面背景色是 #080808 字体颜色则是 #b7b7b7

如有不明白之前请参考改动检索日志！

```scss
$bg-dark-1: #080808 !default; // 深黑色背景色
$bg-dark-2: #252525 !default; // 浅黑色背景色

$dark-font: #b7b7b7 !default; // 字体色

[data-theme="dark"] {
  background-color: $bg-dark-1;
  color: $dark-font;
}
```

> 建议使用上面作为默认黑暗模式样式

如有问题请在下列讨论交流！
